import { SYMBOLS, prizeOdds, playerTotals, jackpotSummary } from "./engine.js";
export const esc = value => String(value ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const art = {
  caps:'<path d="m50 16 8 5 10-1 4 9 9 5-2 10 5 8-6 8-1 10-10 2-7 7-9-4-10 2-5-9-9-4 1-10-5-8 7-8 1-10 10-2z"/><circle cx="49" cy="48" r="20"/><path d="M39 44h20M39 52h20"/>',
  memory:'<path d="M23 61V42q0-24 25-24t25 24v19M27 51h41l8 20H23zM30 71v10m39-10v10M34 38q14-18 28 0M45 25v22"/><circle cx="78" cy="47" r="5"/>',
  mic:'<rect x="36" y="13" width="26" height="44" rx="13"/><path d="M28 41v5a21 21 0 0 0 42 0v-5M49 68v16M34 84h30M40 24h18M40 32h18M40 40h18"/>',
  cocktail:'<path d="m19 31 30 31 30-31zM49 62v21M33 84h32M55 36l16-25M28 41h40"/><circle cx="76" cy="27" r="12"/>',
  hat:'<path d="M10 65q13-23 21-18l18-27 20 27q10-5 21 18-39 20-80 0zM29 48l20 10 21-10M19 65q30 11 61 0"/><path d="m48 34 4 7-7 1z"/>',
  people:'<path d="m50 10 10 11 15 1 2 16 10 12-10 12-2 16-15 1-10 11-10-11-15-1-2-16-10-12 10-12 2-16 15-1z"/><path d="m50 27 6 14 15 1-12 10 4 16-13-8-13 8 4-16-12-10 15-1z"/>'
};
export function symbol(id, label=true, symbols=SYMBOLS) {
  const s=symbols.find(s=>s.id===id) ?? symbols[0];
  return `<span class="gn-symbol gn-${esc(s.id)}"><svg viewBox="0 0 100 100" role="img" aria-label="${esc(s.name)}">${art[s.id]}</svg>${label?`<span>${esc(s.short)}</span>`:""}</span>`;
}
export const bundleLabel = bundle => bundle.map(p=>`${p.quantity}× ${p.name}`).join(' + ');
export function rewardText(r){
  const prizes=r.awards?.length?bundleLabel(r.awards):r.prizes?.length?bundleLabel(r.prizes):'';
  return prizes?`${r.jackpot?'JACKPOT · ':''}${prizes}${r.delivery==='pending'?' · delivery pending':''}`:r.payout?`${r.payout} caps returned`:'No prize';
}
function jackpotPanel(config,summary={}){
  const chance=prizeOdds(config).jackpotRate;
  const trigger=config.jackpotSymbol==='any'?'FIVE MATCHING SYMBOLS':`FIVE ${config.symbols.find(s=>s.id===config.jackpotSymbol)?.name.toUpperCase()}`;
  return `<section class="gn-jackpot" aria-label="Item jackpot"><div><span class="gn-eyebrow">THE MAYOR’S JACKPOT</span><strong>RARE ITEM BUNDLE</strong><p>${esc(bundleLabel(config.prizes.jackpot))}</p></div><div class="gn-jackpot-meta"><b>${esc(trigger)}</b><span>${(chance*100).toFixed(4)}% per spin · ${summary.wins||0} jackpots won</span><span>${summary.spinsSince||0} spins since last jackpot</span></div>${summary.lastWinner?`<p class="gn-last-winner">Last winner: ${esc(summary.lastWinner.name)} · ${esc(new Date(summary.lastWinner.at).toLocaleString())}</p>`:''}</section>`;
}
function lossTable(players){return `<section class="gn-losses"><h2>All-time player losses & prizes</h2><p>Caps lost = sum of each spin’s cap shortfall after refunds. Item value is not deducted. Losing spins award neither caps nor items. Practice spins are excluded.</p><div class="gn-table-scroll"><table><thead><tr><th>Player</th><th>Spins</th><th>Wagered</th><th>Caps back</th><th>Refunds</th><th>Caps lost</th><th>Losing spins</th><th>Items won</th><th>Jackpots</th></tr></thead><tbody>${players.map(p=>{const t=p.totals||playerTotals([]);return `<tr><td>${esc(p.name)}</td>${['spins','wagered','returned','refunded','losses','losingSpins','itemsWon','jackpots'].map(k=>`<td class="${k==='losses'?'negative':''}">${t[k]}</td>`).join('')}</tr>`;}).join('')}</tbody></table></div></section>`;}
export function machineView(s) {
  const c=s.config, o=prizeOdds(c);
  return `<div class="gn-shell">
    <header class="gn-masthead"><span class="gn-eyebrow">EST. 2287 · BOSTON COMMONWEALTH</span><h1>GOOD<span>NEIGHBOR</span></h1><div class="gn-subtitle">${esc(c.name)} <i>★</i> FIVE REEL SLOTS</div></header>
    <div class="gn-status"><span class="gn-dot ${c.paused?'off':''}"></span>${c.paused?'WAGERS PAUSED':c.practice?'PRACTICE · NO CAPS CHARGED':'THE HOUSE IS OPEN'}<span>${s.connected?'CASHIER ONLINE':'CASHIER OFFLINE'}</span></div>
    ${jackpotPanel(c,s.jackpot)}
    <section class="gn-cabinet" aria-label="Five reels"><div class="gn-machine-caption">OF THE PEOPLE. FOR THE PEOPLE.</div><div class="gn-reels ${s.busy?'is-spinning':''}">${(s.reels ?? ['caps','memory','mic','hat','people']).map((id,i)=>`<div class="gn-reel" style="--reel:${i}">${symbol(id,true,c.symbols)}</div>`).join('')}</div><div class="gn-payline">◀ <span>ONE PAYLINE · MATCH 3, 4 OR 5 FROM THE LEFT</span> ▶</div></section>
    <div class="gn-result" role="status" aria-live="polite">${esc(s.message || 'A little luck. A lot of Goodneighbor.')}</div>
    <section class="gn-controls"><label class="gn-character">YOUR CHARACTER<select name="actor" ${s.busy?'disabled':''}><option value="">Choose a character</option>${s.actors.map(a=>`<option value="${esc(a.id)}" ${a.id===s.actorId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><div class="gn-balance"><span>AVAILABLE CAPS</span><strong>${esc(s.balance ?? '—')}</strong></div><div class="gn-wagers"><span>YOUR WAGER</span><div>${c.wagers.map(w=>`<button type="button" data-action="wager" data-wager="${w}" aria-pressed="${w===s.wager}" ${s.busy?'disabled':''}>${w}<small> CAPS</small></button>`).join('')}</div></div><button type="button" class="gn-spin" data-action="spin" ${s.busy||!s.actorId||!s.connected||c.paused?'disabled':''}>${s.busy?'SPINNING…':'SPIN THE REELS'} <span>↻</span></button></section>
    <div class="gn-toolbar"><label><input name="mute" type="checkbox" ${s.mute?'checked':''}> Mute</label><label><input name="motion" type="checkbox" ${s.reduced?'checked':''}> Reduce motion</label>${s.pending?'<button data-action="retry">Check pending spin</button>':''}${s.isGM?'<button data-action="monitor">Overseer console ↗</button>':''}</div>
    <details class="gn-paytable" ${s.paytableOpen?'open':''}><summary>PRIZE TABLE <span>${(o.hitRate*100).toFixed(2)}% win chance</span></summary><table><thead><tr><th>Symbol</th><th>3 match</th><th>4 match</th><th>5 match</th></tr></thead><tbody>${c.symbols.map(x=>`<tr><td>${symbol(x.id,false,c.symbols)} ${esc(x.name)}</td><td>${x.id==='caps'?'Wager back':'Common bundle'}</td><td>Rare bundle</td><td>${c.jackpotSymbol==='any'||c.jackpotSymbol===x.id?'JACKPOT':'Rare bundle'}</td></tr>`).join('')}</tbody></table><p><b>Common:</b> ${esc(bundleLabel(c.prizes.common))}<br><b>Rare:</b> ${esc(bundleLabel(c.prizes.rare))}</p><p>Highest left-to-right match only. Item bundles do not scale with the wager. No wilds or scatters. Items are added to your inventory; delivery problems go to the GM. Each spin is independent.</p></details>
    <footer class="gn-footer">GOOD LUCK OUT THERE, NEIGHBOR. <span>CAP WAGERS · ITEM PRIZES</span></footer></div>`;
}
export function monitorView(s) {
  const filtered=s.events.filter(e=>(!s.filter||e.userId===s.filter)&&(!s.category||e.category===s.category));
  return `<div class="gn-shell gn-console"><header class="gn-console-head"><div><span class="gn-eyebrow">GOODNEIGHBOR SOCIAL CLUB</span><h1>OVERSEER <em>CONSOLE</em></h1></div><span class="gn-live">● LIVE</span></header>
    <div class="gn-console-tools"><button data-action="claim">${s.cashierSelf?'You are the cashier':`Assign me as cashier`}</button><button data-action="pause">${s.config.paused?'Resume wagers':'Pause wagers'}</button><button data-action="prizes">Prize cabinet</button><button data-action="configure">Machine settings</button><button data-action="share">Share machine</button><button data-action="export">Export ledger</button></div><p class="gn-note">Cashier: ${esc(s.cashierName||'Unassigned')} · ${s.config.practice?'Practice mode':'Real caps'} · ${s.config.paused?'Paused':'Open'} · ${s.records.length} recorded spins</p>
    ${jackpotPanel(s.config,jackpotSummary(s.records))}
    <section class="gn-player-grid">${s.players.map(p=>`<article class="gn-player ${p.active?'online':''}"><div><span class="gn-dot ${p.active?'':'off'}"></span><strong>${esc(p.name)}</strong><button data-action="block" data-user="${esc(p.id)}">${s.config.blocked.includes(p.id)?'Allow':'Block'}</button></div><h3>${esc(p.actorName||'No character selected')}</h3><p>${esc(p.status||'Not at machine')}</p><dl><div><dt>CAPS</dt><dd>${esc(p.balance??'—')}</dd></div><div><dt>WAGER</dt><dd>${esc(p.wager??'—')}</dd></div><div><dt>SESSION NET</dt><dd class="${p.net>=0?'positive':'negative'}">${p.net>0?'+':''}${p.net}</dd></div></dl></article>`).join('') || '<p>No players in this world yet.</p>'}</section>
    ${lossTable(s.players)}
    ${s.records.some(r=>!r.practice&&r.delivery==='pending')?`<section class="gn-alert"><h3>Item prizes awaiting delivery</h3>${s.records.filter(r=>!r.practice&&r.delivery==='pending').map(r=>`<div>${esc(r.actorName)} · ${esc(rewardText(r))} <button data-action="deliver" data-actor="${esc(r.actorId)}" data-id="${esc(r.id)}">Deliver prizes</button></div>`).join('')}</section>`:''}
    ${s.pending.length?`<section class="gn-alert"><h3>Settlement review required</h3><p>Reload the world before reviewing an interrupted update. Inspect the saved receipt and caps; never replay an uncertain balance change.</p>${s.pending.map(p=>`<div><code>${esc(p.id)}</code> · ${esc(p.actorName)} · ${esc(p.kind)} <button data-action="reconcile" data-gm="${esc(p.gmId)}" data-id="${esc(p.id)}">Inspect / reconcile</button></div>`).join('')}</section>`:''}
    <div class="gn-feed-heading"><h2>Live activity</h2><select name="filter" aria-label="Filter player"><option value="">All players</option>${s.players.map(p=>`<option value="${esc(p.id)}" ${s.filter===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><select name="category" aria-label="Filter activity"><option value="">All activity</option>${['transaction','jackpot','error','session','admin'].map(c=>`<option value="${c}" ${s.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="gn-feed" role="log">${filtered.slice(0,100).map(e=>`<div class="gn-event ${esc(e.category)}"><time>${esc(new Date(e.at).toLocaleTimeString())}</time><b>${esc(e.userName||'Overseer')}</b><span>${esc(e.text)}</span>${e.spinId?`<button data-action="inspect" data-actor="${esc(e.actorId)}" data-id="${esc(e.spinId)}">Receipt ↗</button>`:''}</div>`).join('')||'<div class="gn-empty">Waiting for the first visitor. Share the machine to invite your players.</div>'}</div>
    <details class="gn-ledger"><summary>Permanent transaction history (${s.records.length})</summary>${s.records.slice(0,100).map(r=>`<div class="gn-event"><time>${esc(new Date(r.at).toLocaleString())}</time><b>${esc(r.actorName)}</b><span>${r.practice?'PRACTICE · ':''}${r.wager} caps → ${esc(rewardText(r))} ${r.refund?'· REFUNDED':''}</span><button data-action="inspect" data-actor="${esc(r.actorId)}" data-id="${esc(r.id)}">Inspect</button></div>`).join('')}<p>Latest 100 shown. Export includes every saved transaction on existing world actors.</p></details></div>`;
}
